[versions]
apache-commons = "1.10.0"
arrow = "1.2.1"
assertk = "0.26.1"
awaitility = "4.2.0"
caffeine = "3.1.8"
detekt = "1.23.1"
fuel = "2.3.1"
groovy = "4.0.13"
guava = "32.1.2-jre"
jackson = "2.15.2"
junit = "5.10.0"
kmongo = "4.10.0"
kotest = "5.7.2"
kotest-spring = "1.1.3"
kotest-wiremock = "2.0.1"
kotlin = "1.9.22"
kotlin-coroutines = "1.7.3"
kotlin-logging = "4.0.0-beta-2"
kotlinter = "4.0.0"
ktor = "2.3.5"
logback = "1.2.11" # logback 1.3+ uses SLF4J 2.x
mockk = "1.13.8"
mockk-spring = "4.0.2"
mongodb-embedded = "4.9.2"
openapi = "1.7.0"
slf4j = "1.7.36"
spock = "2.3-groovy-4.0"
spring-boot = "2.7.10"
spring-cloud = "Hoxton.SR12"
testcontainers-mongodb = "1.19.1"
wiremock = "3.0.1"
nexus-publish = "1.1.0"
intellij-plugin = "1.15.0"

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus-publish" }
intellij = { id = "org.jetbrains.intellij", version.ref = "intellij-plugin" }

[libraries]
# Spring
spring-starter = { group = "org.springframework.boot", name = "spring-boot-starter", version = "" }
spring-starter-cache = { group = "org.springframework.boot", name = "spring-boot-starter-cache", version = "" }
spring-starter-mongodb = { group = "org.springframework.boot", name = "spring-boot-starter-data-mongodb", version = "" }
spring-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test", version = "" }
spring-starter-validation = { group = "org.springframework.boot", name = "spring-boot-starter-validation", version = "" }
spring-cloud-bom = { group = "org.springframework.cloud", name = "spring-cloud-dependencies", version.ref = "spring-cloud" }

# Kotlin
kotlin-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-coroutines-slf4j = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-slf4j", version.ref = "kotlin-coroutines" }
kotlin-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }

# Logging
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
kotlin-logging = { group = "io.github.microutils", name = "kotlin-logging", version.ref = "kotlin-logging" }

# Detekt
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }

# Jackson
jackson-afterburner = { group = "com.fasterxml.jackson.module", name = "jackson-module-afterburner", version.ref = "jackson" }
jackson-avro = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-avro", version.ref = "jackson" }
jackson-jsr310 = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jsr310", version.ref = "jackson" }
jackson-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jackson" }
jackson-xml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-xml", version.ref = "jackson" }
jackson-yaml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-yaml", version.ref = "jackson" }

# Open API
openapi-kotlin = { group = "org.springdoc", name = "springdoc-openapi-kotlin", version.ref = "openapi" }
openapi-ui = { group = "org.springdoc", name = "springdoc-openapi-ui", version.ref = "openapi" }

# Ktor
ktor-client = { group = "io.ktor", name = "ktor-client-core-jvm", version.ref = "ktor" }
ktor-client-apache = { group = "io.ktor", name = "ktor-client-apache", version.ref = "ktor" }
ktor-client-mock = { group = "io.ktor", name = "ktor-client-mock", version.ref = "ktor" }

# Fuel
fuel-core = { group = "com.github.kittinunf.fuel", name = "fuel", version.ref = "fuel" }
fuel-jackson = { group = "com.github.kittinunf.fuel", name = "fuel-jackson", version.ref = "fuel" }

# KMongo
kmongo-core = { group = "org.litote.kmongo", name = "kmongo", version.ref = "kmongo" }
kmongo-coroutine = { group = "org.litote.kmongo", name = "kmongo-coroutine", version.ref = "kmongo" }

# Caffeine
caffeine = { group = "com.github.ben-manes.caffeine", name = "caffeine", version.ref = "caffeine" }

# Commons
apache-commons-csv = { group = "org.apache.commons", name = "commons-csv", version.ref = "apache-commons" }
apache-commons-text = { group = "org.apache.commons", name = "commons-text", version.ref = "apache-commons" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }

# Arrow
arrow-optics = { group = "io.arrow-kt", name = "arrow-optics", version.ref = "arrow" }

# Kotest
kotest-assertions = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-json = { group = "io.kotest", name = "kotest-assertions-json-jvm", version.ref = "kotest" }
kotest-assertions-jvm = { group = "io.kotest", name = "kotest-assertions-core-jvm", version.ref = "kotest" }
kotest-datatest = { group = "io.kotest", name = "kotest-framework-datatest", version.ref = "kotest" }
kotest-property = { group = "io.kotest", name = "kotest-property", version.ref = "kotest" }
kotest-runner = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
kotest-spring = { group = "io.kotest.extensions", name = "kotest-extensions-spring", version.ref = "kotest-spring" }
kotest-wiremock = { group = "io.kotest.extensions", name = "kotest-extensions-wiremock", version.ref = "kotest-wiremock" }

# Spock & Groovy
spock-core = { group = "org.spockframework", name = "spock-core", version.ref = "spock" }
spock-spring = { group = "org.spockframework", name = "spock-spring", version.ref = "spock" }
groovy = { group = "org.apache.groovy", name = "groovy-all", version.ref = "groovy" }
cglib-nodep = { group = "cglib", name = "cglib-nodep", version = "3.3.0" }

# JUnit
junit-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
junit-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }

# Mockk
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
mockk-spring = { group = "com.ninja-squad", name = "springmockk", version.ref = "mockk-spring" }

# Wiremock
wiremock = { group = "com.github.tomakehurst", name = "wiremock", version.ref = "wiremock" }

# MongoDB for tests
mongodb-embedded = { group = "de.flapdoodle.embed", name = "de.flapdoodle.embed.mongo", version.ref = "mongodb-embedded" }
mongodb-embedded-spring = { group = "de.flapdoodle.embed", name = "de.flapdoodle.embed.mongo.spring27x", version.ref = "mongodb-embedded" }
testcontainers-mongodb = { group = "org.testcontainers", name = "mongodb", version.ref = "testcontainers-mongodb" }

# Other testing stuff
assertk = { group = "com.willowtreeapps.assertk", name = "assertk-jvm", version.ref = "assertk" }
awaitility = { group = "org.awaitility", name = "awaitility-kotlin", version.ref = "awaitility" }
